# Generated by Django 5.2.7 on 2025-11-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_en_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dni_cliente_compra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
