# Generated by Django 5.2.7 on 2025-11-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra_dni_cliente_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMovilLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente_movil_local', models.CharField(max_length=150)),
                ('apellido_cliente_movil_local', models.CharField(max_length=150)),
                ('telefono_cliente_movil_local', models.CharField(blank=True, max_length=20, null=True)),
                ('email_cliente_movil_local', models.EmailField(blank=True, max_length=150, null=True)),
                ('direccion_cliente_movil_local', models.CharField(blank=True, max_length=150, null=True)),
                ('dni_cliente_movil_local', models.CharField(max_length=20)),
                ('observaciones_cliente_movil_local', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente móvil local',
                'verbose_name_plural': 'Clientes móviles locales',
                'db_table': 'core_cliente_movil_local',
            },
        ),
    ]
