# Generated by Django 5.2.7 on 2025-11-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientemovillocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_cliente_movil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientemovillocal'),
        ),
    ]
