# Generated by Django 5.2.7 on 2025-11-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_compra_id_cliente_compra_id_cliente_movil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_cliente_movil',
            new_name='id_cliente_movil_local',
        ),
    ]
