# Generated by Django 5.2.7 on 2025-11-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_cliente_movil_compra_id_cliente_movil_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='dni_cliente_compra',
        ),
    ]
