# Generated by Django 5.2.7 on 2025-11-16 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitudcontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcontacto',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
